### ISSUE TITLE
26日までのタスクの割り振り

### ISSUE THREAD

**Issue by shkpo** [moneywoods/GAA2019#5]
- カメラ: shakedpotato
- 3Dモデルへの置き換え: shakedpotato
- ステージスタート, クリア演出: shakedpotato
- ステージセレクト: Daijiro123
- ステージの遷移情報(次のステージとか): Daijiro123
- 3Dモデルのアニメーションの実装: RNY1120 & 宮本知昂

26日がα版〆切ですがんばりましょう

**Comment by KAPPAOFFLINE** [comment]
感謝します
